<?php
	$_productCollection=$this->getLoadedProductCollection();
	$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

		
			<div class="tab-prod" role="tabpanel">
				<div class="col-md-3"><h3>Featured product</h3></div>
				
			</div>
			<div class="clearfix"></div>
			<div class="category-products">
				<?php $_collectionSize = $_productCollection->count() ?>
				<?php $_columnCount = $this->getColumnCount(); ?>

				<?php $i=0; foreach ($_productCollection as $_product): ?>

					<?php if ($i++%$_columnCount==0): ?>

						<div class="slider1">
							<?php endif; ?>
							<div class="img-pro item <?php if(($i-1)%$_columnCount==0): ?> 
								first<?php elseif($i%$_columnCount==0): ?> 
								last
								<?php endif; ?>"> 
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)?>" >
					           		<img class="img-front" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,310); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'),
											null, true) ?>" />
					            	<img class="img-back" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,310); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'),
											null, true) ?>" />
					          	</a>
								<h4 class="panel-title product-name">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null,true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
									</a>
								</h4>
								<div class="pull-left"> <?php echo $this->getPriceHtml($_product, true) ?> </div>
								<div class="sticker">NEW</div>
								<div class="actions">
									<?php if($_product->isSaleable()): ?>
										<button type="button" class="button btn-cart pull-left" data-toggle="tooltip" data-placement="top"  title="<?php echo $this->__('Add to Cart') ?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></button>
										<?php else: ?>
										<p class="btn btn-alert availability out-ofstock">
											<span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									<ul class="add-to-links pull-left">
					                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
					                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist fa fa-heart" data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Wishlist') ?>"><span><?php echo $this->__('Add to Wishlist') ?></span></a></li>
					                    <?php endif; ?>
					                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
					                         <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare fa fa-refresh" data-original-title="Add to Compare" rel="tooltip"data-toggle="tooltip" data-placement="top"  title="<?php echo $this->__('Add to Compare') ?>"><span><?php echo $this->__('Add to Compare') ?></span></a></li>
					                    <?php endif; ?>
					                    
					                </ul>
								</div>          
							</div>
							<?php if ($i==5) break; ?>
							<?php if ($i%$_columnCount==0 || $i==$_collectionSize):
							?>
						</div>
					<?php endif; ?>
				<?php endforeach; ?>
				</div>
			</div>

<?php endif; ?>